{
 "title": "CRKI",
 "time": { "from": "2020-12-06T13:31:12.457Z", "to": "2021-03-07T23:48:03.808Z" },
 "panels": [
  {
   "title": "Number vaccines",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  vaccines AS metric,\n  daily_vaccinations\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "Number vaccine per day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  vaccines AS metric,\n  daily_vaccinations AS \"daily_vaccinations\"\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  },
  {
   "title": "daily vaccination per region",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM country_vaccinations\nORDER BY date"
    }
   ]
  }
 ]
}